* Init file(and directory) Quick Access.

  [[https://melpa.org/#/iqa][https://melpa.org/packages/iqa-badge.svg]]

** Trivia
   Sadly, Emacs (unlike [[http://spacemacs.org/][Spacemacs]], which has [[http://spacemacs.org/doc/QUICK_START.html#dotfile-spacemacs][spacemacs/find-dotfile]]) doesn't have
   a function to open its own init file, so thousands of users have to write their owns.
   I'm not different :)

** Installation

   Using [[https://github.com/jwiegley/use-package][use-package]]:

   #+begin_src emacs-lisp
     (use-package iqa
       ;; use this if your config is generated from org file
       ;; :custom
       ;; (iqa-user-init-file (concat user-emacs-directory "README.org") "Edit README.org by default.")
       ;; bind iqa functions to shortcuts
       :bind (:map ctl-x-map
                   ("M-f" . iqa-find-user-init-file)
                   ("M-c" . iqa-find-user-custom-file)
                   ("M-r" . iqa-reload-user-init-file)
                   ("M-d" . iqa-find-user-init-directory))
       ;; :config
       ;; (iqa-add-bookmarks) — to add bookmarks to emacs init files
       ;; (iqa-setup-default) - to bind default bindings
       )
   #+end_src

   or just put /iqa.el/ to ~load-path~ and

   #+begin_src emacs-lisp
     (require 'iqa)
     (iqa-setup-default)
   #+end_src

** Info

   ~iqa-find-user-init-file~ is a shorthand to open user init file.
   By default ~user-init-file~ is used.  If your configuration is generated
   from org-mode source you may want to point it to your org file.
   #+begin_src emacs-lisp
     (setq iqa-user-init-file (concat user-emacs-directory "init.org"))
   #+end_src

   File is opened by ~find-file~ but you can redefine it by e.g.

   #+begin_src emacs-lisp
     (setq iqa-find-file-function #'find-file-other-window)
   #+end_src

   ~iqa-reload-user-init-file~ reloads ~user-init-file~ (not ~iqa-user-init-file~)

   For a full restart take a look at [[https://github.com/iqbalansari/restart-emacs][restart-emacs]] package.

   ~iqa-find-user-init-directory~ opens init file directory


   ~iqa-setup-default~ defines keybindings:

   /C-x M-f/ — ~iqa-find-user-init-file~

   /C-x M-c/ — ~iqa-find-user-custom-file~

   /C-x M-r/ — ~iqa-reload-user-init-file~

   /C-x M-d/ — ~iqa-find-user-init-directory~


   If you don't like these, or prefer to use Emacs bookmarks instead, ~iqa-add-bookmarks~
   adds bookmarks to these files.
