* Init file(and directory) Quick Access.

** Trivia
   Sadly, Emacs (unlike [[http://spacemacs.org/][Spacemacs]], which has [[http://spacemacs.org/doc/QUICK_START.html#dotfile-spacemacs][spacemacs/find-dotfile]]) doesn't have
   a function to open its own init file, so thousands of users have to write their owns.
   I'm not different :)

** Installation

   Using [[https://github.com/jwiegley/use-package][use-package]] and [[https://github.com/quelpa/quelpa-use-package][quelpa-use-package]]:

   #+begin_src emacs-lisp
     (use-package iqa
       :ensure nil
       :quelpa
       (iqa :repo "a13/iqa.el" :fetcher github :version original)
       ;; for generated files only
       ;; :init
       ;; (setq iqa-user-init-file (concat user-emacs-directory "init.org"))
       :config
       (iqa-setup-default))
   #+end_src

   or just put /iqa.el/ to ~load-path~ and

   #+begin_src emacs-lisp
     (require 'iqa)
   #+end_src

** Info

   ~iqa-find-user-init-file~ is a shorthand to open user init file.
   By default ~user-init-file~ is used.  If your configuration is generated
   from org-mode source you may want to point it to your org file.
   #+begin_src emacs-lisp
     (setq iqa-user-init-file (concat user-emacs-directory "init.org"))
   #+end_src

   File is opened by ~find-file~ but you can redefine it by e.g.

   #+begin_src emacs-lisp
     (setq iqa-find-file-function #'find-file-other-window)
   #+end_src

   ~iqa-reload-user-init-file~ reloads ~user-init-file~ (not ~iqa-user-init-file~)

   For a full restart take a look at [[https://github.com/iqbalansari/restart-emacs][restart-emacs]] package.

   ~iqa-find-user-init-directory~ opens init file directory


   ~iqa-setup-default~ defines keybindings:

   /C-x M-f/ — ~iqa-find-user-init-file~

   /C-x M-r/ — ~iqa-reload-user-init-file~

   /C-c M-d/ — ~iqa-find-user-init-directory~
